Dispatch types

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -169,13 +169,13 @@ replay () {
 
 execute () {
     pgm="bin/why3execute$suffix"
-    printf "  $1 $2... "
-    if $pgm $1 $2 > /dev/null; then
+    echo -n "  $@... "
+    if "$pgm" "$@" > /dev/null; then
         echo "ok"
     else
-        echo "execution test failed!"
-        echo $pgm $1 $2
-        $pgm $1 $2
+        echo "execution test failed! $?"
+        echo $pgm $@
+        "$pgm" "$@"
         exit 1
     fi
 }
@@ -317,7 +317,7 @@ rac () {
     for func in $@; do
         echo "** $mod.$func"
         echo -n " $func" >&2
-        "bin/why3execute$suffix" --rac "${RAC_OPTIONS[@]}" "$file" "$mod.$func" 2>&1
+        "bin/why3execute$suffix" --rac "${RACARGS[@]}" "$file" "$mod.$func" 2>&1
     done
     echo >&2
 }
@@ -408,7 +408,7 @@ output="examples/tests/rac.out"
     rac "$mlw" RecordPoly test1 test2 test3
     rac "$mlw" PolyFunc test0 test1
     rac "$mlw" ArrayExec test0 test1 test2
-    (RAC_OPTIONS=( -L examples/tests --dispatch=array.Array-rac.ArrayExec )
+    (RACARGS=( -L examples/tests --dispatch=array.Array-rac.ArrayExec )
      rac "$mlw" Arrays test0) # TODO test1
 ) > "$output"
 if git diff --exit-code --src-prefix=EXPECTED/ --dst-prefix=ACTUAL/ "$output"; then
@@ -422,6 +422,7 @@ fi
 
 if enabled execution; then
 echo "=== Checking execution ==="
+DISPATCH=( -L examples/tests --dispatch=array.Array-rac.ArrayExec )
 execute examples/euler001.mlw Euler001.bench
 execute examples/euler002.mlw Solve.bench
 execute examples/fibonacci.mlw FibRecGhost.bench
@@ -432,20 +433,20 @@ execute examples/fibonacci.mlw FibonacciLogarithmic.bench
 # execute examples/same_fringe.mlw SameFringe.test5
 execute examples/same_fringe.mlw Test.test1
 execute examples/vstte12_combinators.mlw Combinators.test_SKK
-echo Ignoring: execute examples/selection_sort.mlw SelectionSort.bench
-echo Ignoring: execute examples/insertion_sort.mlw InsertionSort.bench
-echo Ignoring: execute examples/quicksort.mlw Test.bench
-echo Ignoring: execute examples/conjugate.mlw Test.bench
+execute "${DISPATCH[@]}" examples/selection_sort.mlw SelectionSort.bench
+execute "${DISPATCH[@]}" examples/insertion_sort.mlw InsertionSort.bench
+execute "${DISPATCH[@]}" examples/quicksort.mlw Test.bench
+execute "${DISPATCH[@]}" examples/conjugate.mlw Test.bench
 # fails: needs support for "val" without code (how to do it?)
 # examples/vacid_0_sparse_array.mlw Harness.bench
-echo Ignoring: execute examples/knuth_prime_numbers.mlw PrimeNumbers.bench
-echo Ignoring: execute examples/vstte10_max_sum.mlw TestCase.test_case
-echo Ignoring: execute examples/verifythis_fm2012_LRS.mlw LCP_test.bench
-echo Ignoring: execute examples/verifythis_fm2012_LRS.mlw SuffixSort_test.bench
-echo Ignoring: execute examples/verifythis_fm2012_LRS.mlw SuffixArray_test.bench
-echo Ignoring: execute examples/verifythis_fm2012_LRS.mlw LRS_test.bench
-echo Ignoring: execute examples/verifythis_PrefixSumRec.mlw PrefixSumRec.bench
-echo Ignoring: execute examples/vstte10_queens.mlw NQueens.test8
+execute "${DISPATCH[@]}" examples/knuth_prime_numbers.mlw PrimeNumbers.bench
+execute "${DISPATCH[@]}" examples/vstte10_max_sum.mlw TestCase.test_case
+execute "${DISPATCH[@]}" examples/verifythis_fm2012_LRS.mlw LCP_test.bench
+execute "${DISPATCH[@]}" examples/verifythis_fm2012_LRS.mlw SuffixSort_test.bench
+execute "${DISPATCH[@]}" examples/verifythis_fm2012_LRS.mlw SuffixArray_test.bench
+execute "${DISPATCH[@]}" examples/verifythis_fm2012_LRS.mlw LRS_test.bench
+execute "${DISPATCH[@]}" examples/verifythis_PrefixSumRec.mlw PrefixSumRec.bench
+execute "${DISPATCH[@]}" examples/vstte10_queens.mlw NQueens.test8
 # fails: "Cannot decide condition of if: (not ((~)((<<)((~)(0), 8)) = 0))"
 # examples/queens.mlw NQueensBits.test8
 # fails: cannot find definition of routine eq
