Add a 'replay' section to the bench when replaying does not involve any prover.

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -74,7 +74,7 @@ drivers () {
 valid_goals () {
     pgm="bin/why3prove$suffix"
     for f in $1/*.mlw; do
-	printf "  "$f"... "
+	printf "  $f... "
 	if $pgm -t 10 -P alt-ergo $f | grep -q -v Valid; then
 	    echo "valid test $f failed!"
 	    echo "$pgm -P alt-ergo $f"
@@ -89,7 +89,7 @@ valid_goals () {
 invalid_goals () {
     pgm="bin/why3prove$suffix"
     for f in $1/*.mlw; do
-	printf "  "$f"... "
+	printf "  $f... "
 	if $pgm -t 3 -P alt-ergo $f | grep -q Valid; then
 	    echo "invalid test $f failed!"
 	    echo "$pgm -P alt-ergo $f"
@@ -98,6 +98,21 @@ invalid_goals () {
         else
 	    echo "ok"
        fi
+    done
+}
+
+replay () {
+    pgm="bin/why3replay$suffix"
+    for f in $1/*/; do
+        printf "  $f... "
+        if $pgm $f > /dev/null; then
+            echo "ok"
+        else
+            echo "replay test failed!"
+            echo $pgm $f
+            $pgm $f
+            exit 1
+        fi
     done
 }
 
@@ -212,6 +227,10 @@ goods examples/avl "-L examples/avl"
 goods examples/verifythis_2016_matrix_multiplication "-L examples/verifythis_2016_matrix_multiplication"
 goods examples/double_wp "-L examples/double_wp"
 goods examples/in_progress
+echo ""
+
+echo "=== Checking replay (no prover) ==="
+replay bench/replay
 echo ""
 
 echo "=== Checking valid goals ==="
