improved bench for extraction

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -81,19 +81,29 @@ execute () {
 extract_and_run () {
     echo -n "$1... "
     rm -f $1/$2
-    if make -C $1 > /dev/null 2>&1; then
-       if $1/main.opt $3 > /dev/null 2>&1; then
-           echo "ok"
-       else
-           echo "execution failed!"
-           echo $1/main.opt $3
-           $1/main.opt $3
-           exit 1
-       fi
+    echo -n "extract... "
+    if make -C $1 extract > /dev/null 2>&1; then
+        echo -n "compile... "
+        if make -C $1 > /dev/null 2>&1; then
+           echo -n "execute... "
+           if $1/main.opt $3 > /dev/null 2>&1; then
+              echo "ok"
+           else
+              echo "execution failed!"
+              echo $1/main.opt $3
+              $1/main.opt $3
+              exit 1
+           fi
+        else
+            echo "compilation failed!"
+            echo make -C $1 
+            make -C $1 
+            exit 1
+        fi
     else
-        echo "extract or compilation failed!"
-        echo make -C $1
-        make -C $1
+        echo "extract failed!"
+        echo make -C $1 extract
+        make -C $1 extract
         exit 1
     fi
 }
