Documentation: add description to all the registration functions  (metas, debug flags, transformations, formats) except for label.
This description is used in --list-*. The description can use any of
the formatting markup of Format "@ " "@[",...

Transformations can also specify from which metas and labels they
depend, and add informations about how they are interpreted.

TODO:
  - complete and correct the documentation
  - when a transformation use Trans.on_meta, it should be possible to
    add an interpretation of the metas in the documentation.
  - recover a summary version of --list-* ?
  - be able to export in latex?

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -98,6 +98,18 @@ valid_goals () {
     done
 }
 
+list_stuff () {
+    echo -n "$1 "
+    if $pgml $1 > /dev/null 2>&1; then
+        echo "ok"
+    else
+        echo "$pgm $1 FAIL"
+        $pgm $1
+        exit 1
+    fi
+}
+
+
 echo "=== Checking drivers ==="
 drivers drivers
 echo ""
@@ -154,3 +166,11 @@ echo "=== Checking valid goals ==="
 valid_goals bench/valid
 echo ""
 
+echo "=== Checking --list-* ==="
+list_stuff --list-transforms
+list_stuff --list-printers
+list_stuff --list-provers
+list_stuff --list-formats
+list_stuff --list-metas
+list_stuff --list-debug-flags
+echo ""
