Use Z3,4.8.10 in ce-bench and check-ce-bench scripts

diff --git a/bench/check-ce-bench b/bench/check-ce-bench
--- a/bench/check-ce-bench
+++ b/bench/check-ce-bench
@@ -102,7 +102,8 @@ run () {
 	    echo "FAILED!"
 	    echo "diff is the following:"
 	    echo "$f"
-	    diff -u <(echo "$str_oracle") <(echo "$str_out")|colorize
+	    (diff -u <(echo "$str_oracle") <(echo "$str_out") \
+        || [ $? -eq 1 ])|colorize
 	    failed="$failed$f\n"
 	    success=false
 	fi
@@ -119,8 +120,8 @@ for file in $files; do
     printf "Running provers on $filedir/$filebase.mlw\n";
     run CVC4,1.7 $filedir $filebase true   150000
     run CVC4,1.7 $filedir $filebase false  150000
-    run Z3,4.8.4 $filedir $filebase true  7500000
-    run Z3,4.8.4 $filedir $filebase false 7500000
+    run Z3,4.8.10 $filedir $filebase true  7500000
+    run Z3,4.8.10 $filedir $filebase false 7500000
 done
 
 # Check the reproduction of the experiments by Petion (2018). Use CVC4 because
@@ -129,9 +130,9 @@ bench/check-ce/petiot2018/experiments.sh --prover CVC4,1.7 \
   --ce-prover CVC4,1.7,counterexamples --stepslimit 10000 --rac-prover CVC4,1.7
 
 if [ "$success" = true ]; then
-    echo "Check-ce bench: success"
+    echo "check-ce-bench: success"
     exit 0
 else
-    printf "\nCheck-ce bench: failed\n$failed\n"
+    printf "\ncheck-ce-bench: failed for the following files\n$failed\n"
     exit 1
 fi
