infer-bench: allow to specify why3 libs in the arguments of the script

diff --git a/bench/infer-bench b/bench/infer-bench
--- a/bench/infer-bench
+++ b/bench/infer-bench
@@ -13,6 +13,7 @@ files=""
 dirs=""
 success=true
 why3prove="bin/why3prove"
+why3libs=""
 
 if test $# = 0; then
   printf "no files provided\n"
@@ -20,31 +21,36 @@ if test $# = 0; then
 fi
 
 while test $# != 0; do
-case "$1" in
-  "-update-oracle")
-      updateoracle=true;;
-  "-force-update-oracle")
-      forceupdateoracle=true;;
-  "-"*)
-      printf "unknown option: %s\n" "$1"
-      printf "usage: infer-bench [-update-oracle] <file>\n"
-      printf "  if <file> is a directory, it runs on all the *.mlw files\n"
-      exit 2;;
-  *)
-    if [ -d "$1" ]; then
-      dirs="$dirs $1"
-    else
-      if [ -f "$1" ]; then
-        files="$files $1"
+  case "$1" in
+    "-update-oracle")
+        updateoracle=true;;
+    "-force-update-oracle")
+        forceupdateoracle=true;;
+    -L=?*)
+        why3libs="$why3libs ${1#*=}";;
+    "-"*)
+        printf "unknown option: %s\n" "$1"
+        printf "usage: infer-bench [-update-oracle] <file>\n"
+        printf "  if <file> is a directory, it runs on all the *.mlw files\n"
+        exit 2;;
+    *)
+      if [ -d "$1" ]; then
+        dirs="$dirs $1"
       else
-        echo "File not found: $1"
-        exit 2
+        if [ -f "$1" ]; then
+          files="$files $1"
+        else
+          echo "File not found: $1"
+          exit 2
+        fi
       fi
-    fi
-
-esac
-shift
+  esac
+  shift
 done
+
+if test -n "$why3libs"; then
+   why3libs="-L $why3libs"
+fi
 
 for d in $dirs; do
   d=$(echo $d | sed 's:/*$::') #remove trailling slashs
@@ -61,7 +67,7 @@ run () {
   file_dir="$(dirname $1)"
   out_file="$file_dir/${file_base%.*}.out"
   oracle_file="$file_dir/${file_base%.*}.oracle"
-  $why3prove $1 -t 1 -P alt-ergo --debug=print-inferred-invs > "$out_file" 2>&1
+  $why3prove $1 -t 1 -P alt-ergo --debug=print-inferred-invs $why3libs > "$out_file" 2>&1
   str_out=$(sed 's/[0-9]\+\.[0-9]\+s//g' $out_file | sed 's/[0-9]\+ steps//g')
   str_oracle=$(sed 's/[0-9]\+\.[0-9]\+s//g' $oracle_file | sed 's/[0-9]\+ steps//g')
   if [ "$str_oracle" = "$str_out" ] ; then
